### ISSUE TITLE
не правильно определяет справедливую стоимость по ВСЕМ бумагам

### ISSUE THREAD

**Issue by slavb18** [ilb/cloudtreasury#111]
Пример: облигация ГТЛК 2P-01
расчет на 30.08 выдает данные (скрин1 )
справедливая стоимость 992,4
Количество дней, в которые заключались сделки 20

а должны быть данные:
справедливая стоимость 992,2
Количество дней, в которые заключались сделки 35

Ну и количество сделок и суммарный объем торгов соответственно тоже 
считает не правильно.

Сайт, откуда подтягиваются данные работает, такое ощущение что программа 
расчета подтягивает итоги торгов не за все дни нужного периода.
![screen01](https://github.com/user-attachments/assets/ae2e9a0c-b0e8-4070-9c3e-d2c41caec74b)
[mfd.zip](https://github.com/user-attachments/files/16940000/mfd.zip)

**Comment by slavb18** [comment]
сегодня опять те же неполадки
не корректно определяет справедливую стоимость по ВСЕМ бумагам.
Пример: облигация ГТЛК 2P-01
расчет за 04.09 выдает данные (скрин1 )
справедливая стоимость 994,2
Количество дней, в которые заключались сделки 32

а должны быть данные: (скрин2)
справедливая стоимость 994,5
Количество дней, в которые заключались сделки 33

Ну и количество сделок и суммарный объем торгов соответственно тоже 
считает не правильно.

Сайт, откуда подтягиваются данные работает и так же выдает цену 994,5 
(Скрин3), такое ощущение что программа расчета не подтянула итоги 
торгов  за 04.09.т.к. такая цена (994,2) была 03.09.
Посмотрите, плиз...

**Comment by pivotdude** [comment]
При загрузке файлов с сайта вместо файла, fetch загружает ddos защиту и в csv файл попадает следующая информация:
```
<!doctype html><html><head><title>DDoS-Guard</title><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="stylesheet" href="/.well-known/ddos-guard/js-challenge/index.css"><script defer="defer" src="/.well-known/ddos-guard/js-challenge/view.js"></script><script defer="defer" src="/.well-known/ddos-guard/js-challenge/index.js"></script><script src="https://check.ddos-guard.net/check.js"></script></head><body data-ddg-origin="true" data-ddg-l10n="true"><div class="container"><div class="top"><h1 id="ddg-l10n-title">Checking your browser before accessing <span class="ddg-origin"></span></h1><p id="ddg-l10n-description">Please wait a few seconds. Once this check is complete, the website will open automatically</p><img id="ddg-img-loading" src="" alt="loading"/></div><div class="bottom"><div class="link-container"><span class="bottom-text" id="ddg-l10n-link-text">Protected by <a href="https://ddos-guard.net/en?utm_medium=preloader" target="_blank" id="ddg-link">DDos-Guard</a></span></div></div></div></
```
Из за чего не удаётся получить информацию о бумагах.

**Comment by slavb18** [comment]
При построении данных за 05.09. снова не корректно определяет 
справедливую стоимость по ВСЕМ бумагам. :-(
Пример: облигация РЖД-30 обл
расчет за 04.09 выдает данные (скрин1 )
справедливая стоимость 980,4
Количество дней, в которые заключались сделки 30

а должны быть данные: (скрин2)
справедливая стоимость 977,5
Количество дней, в которые заключались сделки 34

Ну и количество сделок и суммарный объем торгов соответственно тоже 
считает не правильно.

Сайт, откуда подтягиваются данные работает и так же выдает цену 977,5 
(Скрин3), такое ощущение что программа расчета не подтянула итоги 
торгов  за последние 4 дня и выдала расчеты за 30.08 .т.к. такая цена 
(980,4) была 30.08., и так по все бумагам

**Comment by slavb18** [comment]
@pivotdude почему то качает данные за июль, хотя должен брать скачанные ?

│ Response to https://mfd.ru/marketdata/endofday/5/moex_shares_2024_07_24.csv returned <!doctype html><html><head><title>DDoS-Guard</title><meta charset="utf-8"/><me │
│ Response to https://mfd.ru/marketdata/endofday/5/moex_shares_2024_07_24.csv returned <!doctype html><html><head><title>DDoS-Guard</title><meta charset="utf-8"/><me │
│ Response to https://mfd.ru/marketdata/endofday/5/moex_shares_2024_07_24.csv returned <!doctype html><html><head><title>DDoS-Guard</title><meta charset="utf-8"/><me │
│ Response to https://mfd.ru/marketdata/endofday/5/moex_shares_2024_07_24.csv returned <!doctype html><html><head><title>DDoS-Guard</title><meta charset="utf-8"/><me │
│ exception Error: HTTP error: Max retries reached with DDoS-Guard detection                                                                                          │
│     at FileBrowser._browseInternet (/app/.next/server/chunks/8250.js:490:19)

**Comment by pivotdude** [comment]
Такой файл уже есть с данными и он ещё раз его загружает?

**Comment by slavb18** [comment]
> Такой файл уже есть с данными и он ещё раз его загружает?

Наверное чистится из-за того, что tmpdir https://github.com/ilb/cloudtreasury/blob/abe30488be199e1b51ffbde69efbe85f69ae8992/src/libs/FairPriceCalc/FileBrowser.mjs#L14

Предлагаю добавить переменную 
```
        - name: DATA_DIR
          value: "/var/apps/{{ $.Values.werf.name }}"
```
И заменить путь на DATA_DIR/mfd например

**Comment by pivotdude** [comment]
> > Такой файл уже есть с данными и он ещё раз его загружает?
> 
> Наверное чистится из-за того, что tmpdir
> 
> https://github.com/ilb/cloudtreasury/blob/abe30488be199e1b51ffbde69efbe85f69ae8992/src/libs/FairPriceCalc/FileBrowser.mjs#L14
> 
> Предлагаю добавить переменную
> 
> ```
>         - name: DATA_DIR
>           value: "/var/apps/{{ $.Values.werf.name }}"
> ```
> 
> И заменить путь на DATA_DIR/mfd например

Ну файлы не будут удалятся после перезагрузки, проблему с ddos это не решит. Может быть если !response.ok, вот так сделать (chatGPT): 
```js
1. Использование Puppeteer или Playwright
Эти библиотеки позволяют эмулировать действия пользователя в браузере, включая прохождение JavaScript-капчи или проверки, подобные DDoS Guard. Вы можете использовать Puppeteer или Playwright для автоматизации процесса загрузки файлов.

Puppeteer:

javascript
Копировать код
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('URL_с_файлом');
  
  // Ждем 10 секунд для прохождения проверки DDoS Guard
  await page.waitForTimeout(10000);

  // Начинаем загрузку файла
  const downloadPath = './downloads';
  await page._client().send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath});
  
  // Эмулируем нажатие на ссылку для скачивания
  await page.click('a.download-link-selector');
  
  await browser.close();
})();
Playwright (аналогично, но с другой API):

javascript
Копировать код
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('URL_с_файлом');
  
  // Ждем 10 секунд
  await page.waitForTimeout(10000);

  // Устанавливаем папку для загрузок
  await page.setDownloadBehavior({ behavior: 'allow', downloadPath: './downloads' });

  // Эмулируем нажатие для загрузки файла
  await page.click('a.download-link-selector');

  await browser.close();
})();


```

**Comment by pivotdude** [comment]
Предлагаю вот так сделать:
```js
import axios from 'axios';
import { ddosGuardBypass } from 'axios-ddos-guard-bypass';
import { CookieJar } from 'tough-cookie';
import fs from 'fs'

let serviceUrl = 'https://mfd.ru/marketdata/endofday/5/moex_shares_2024_09_09.csv';
let headers = {
  Referer: serviceUrl
};

let cookieJar = new CookieJar();
let agent = axios.create({
  jar: cookieJar,
  responseType: 'stream' // Это важно для работы с потоками
});

ddosGuardBypass(agent);

try {
  let response = await agent({
    url: serviceUrl,
    headers: headers
  });

  // Создаем поток записи в файл
  const writer = fs.createWriteStream('moex_shares_2024_09_09.csv');

  // Пайпим данные ответа в поток записи
  response.data.pipe(writer);

  // Печатаем статус и информацию о том, что запись началась
  console.log('Файл загружается и сохраняется как moex_shares_2024_09_09.csv');

  // Дожидаемся завершения записи
  writer.on('finish', () => {
    console.log('Файл успешно сохранен.');
  });

  writer.on('error', (err) => {
    console.error('Ошибка записи файла:', err);
  });

} catch (error) {
  console.error('Ошибка запроса:', error);
}
```
Через Puppeteer запрос не работает.
