### ISSUE TITLE
Ошибки в расчетах

### ISSUE THREAD

**Issue by slavb18** [ilb/cloudtreasury#9]
1  . Дата отчета проставляется не верно (ячейка В1), должна быть дата 12.09.2022
2. В отчет не попала бумага ЕАБР 1Р-04. По ней произошел сбой в расчете.
При расчете вышла ошибка (Скрин00), хотя на старом ресурсе https://devel.net.ilb.ru/workflowfront/workList расчет строится правильно (Скрин01)
3. При заведении данных в столбец отчета «Цена сделки (приобретения ценной бумаги), руб..» не происходит расчет в столбце отчета « Существенность отклонения, %%  (не более 10%)» .
4. в столбце отчета  «Исходные данные 1-го уровня - Активный рынок, 1-й уровень исходных данных: (ДА/НЕТ)» необходимо чтобы выходил итог  ДА/НЕТ, а не true/false.
[12092022_Определение СС.xls](https://github.com/ilb/cloudtreasury/files/9553705/12092022_.xls)

[2022-09-12.xlsx](https://github.com/ilb/cloudtreasury/files/9553703/2022-09-12.xlsx)

**Comment by MaximumQuiet** [comment]
Разбил на отдельные issue
